# Site settings
baseurl = "https://dongdieu.edu.vn"
languageCode = "en-us"
title = "DongDieu English Center"
theme = "syna"
enableGitInfo = false
version = "0.17.3"

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "DongDieu"
  description = "DongDieu English Center"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "images/dongdieu32.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "images/favicon.png"
  

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#2196f373"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/gioi-thieu"
  name = "Giới thiệu"
  weight = 10

[[menu.main]]
  url = "/khoa-hoc"
  name = "Khoá học"
  weight = 20

[[menu.main]]
  url = "/tin-tuc"
  name = "Tin tức"
  weight = 30

[[menu.main]]
  url = "#"
  name = "Thư viện"
  weight = 40

[[menu.main]]
  url = "/lien-he"
  name = "Liên hệ"
  weight = 50


[[menu.copyright_footer]]
  url = "/lien-he"
  name = "Thông tin liên hệ"
  weight = 10

